import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex w-full h-screen  bg-white">
          <article className="relative w-full laptop:w-3/4 flex flex-col px-10 gap-5 h-full overflow-auto overflow-x-hidden ">
            {children}
          </article>
        </main>
      </body>
    </html>
  );
}
